fos_rest:
  versioning:
    enabled: true
    resolvers:
      custom_header: true
    default_version: '1.0'
  format_listener:
    enabled: true
    rules:
      - { path: '^/api/*', priorities: [ 'text/html', '*/*' ], fallback_format: html, prefer_extension: true }
      - { path: '^/*',  priorities: [ 'json' ], fallback_format: json, prefer_extension: false }
  body_converter:
    enabled: true
    validate: true
    validation_errors_argument: validationErrors
