framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false

    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    php_errors:
        log: true

    http_client:
        scoped_clients:
            user.client:
                base_uri: '%env(USER_SERVICE_HOST)%'
                headers:
                    Content-Type: 'application/json'
                    X-Accept-Version: '1.0'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
